language: c
compiler:
  - gcc
before_install:
  - git clone -b devel git://github.com/nim-lang/Nim.git --depth 1
  - cd Nim
  - git clone --depth 1 git://github.com/nim-lang/csources
  - cd csources && sh build.sh
  - cd ..
  - bin/nim c koch
  - ./koch boot -d:release
  - export PATH=$PWD/bin:$PATH
  - cd ..
script:
- nim --version
- nim c --run test.nim
# TODO find out how to use newer node JS - does not seem to work with old version 8
#- nim js -d:nodejs --run test.nim 

